- src/readme.ts
Just noticed that the link still pointed to the now archived repo.
I don't know why the Github UI appended a newline when editing the file. Feel free to remove it.
> update link to cdktf-provider-project

- src/index.ts
Workaround for error from nuget.org when trying to publish with package id "HashiCorp.Cdktf.Providers.Aws":
> Response status code does not indicate success: 409 (The package ID is reserved. You can upload your package with a different package ID. Reach out to support@nuget.org if you have questions.).
> Workaround nuget complaining about AWS provider naming

- src/index.ts
Turned out that https://github.com/terraform-cdk-providers/cdktf-provider-project/pull/102 wasn't necessary. The issue was due to `HashiCorp` as prefix for nuget `packageids` being pro-actively and automatically reserved by Nuget. We were able to resolve this with the Nuget support.
> Drop obsolete workaround

- src/cdktf-config.ts
cdktf has been on version `0.2.0`, as of 21 days ago , and recently got bumped up to` 0.2.1`.
Using `^0.1` locks semvar resolution to version `0.1.0 - 0.1.9`
Anyone who wants to use the prebuilt providers with the latest cdktf release, can end up in dependency `warning` hell.
Using `^0.x` locks semvar resolution to version `0.0.0` - `< 1.0.0`.
IMO, it's a fair play to allow the flexibility of the lib, especially before a 1.0 release, we can go back to locking on major/minor versions once 1.0 is released.
Moving fast and breaking things is a lifestyle, especially in pre 1.0 land  :)
Not to mention, having the GitHub action workflows is a safety net for breaking changes, so any provider using this package as a base wouldn't really be at risk of being unexpectedly updated and affecting …
> Update cdktf version to a more flexible semvar.

- src/cdktf-config.ts
- yarn.lock
There are issues with defining the version like `^0` / `<1` / `0.x` when
building packages for nuget. Haven't fully grasped what the issue is, a
fix should be done in [jsii-pacmak](https://github.com/aws/jsii/blob/3e154b5c558f87a791322607b424ff53556a98fe/packages/jsii-pacmak). In general, it should be [supported](https://github.com/aws/jsii/blob/3e154b5c558f87a791322607b424ff53556a98fe/packages/jsii-pacmak/test/targets/version-utils.test.ts)
The version schema for nuget is here https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges-and-wildcards
The error we're seeing:
```
/tmp/npm-packf3Ti8l/HashiCorp.Cdktf.Providers.Aws/HashiCorp.Cdktf.Providers.Aws.csproj : warning NU1604: Project dependency HashiCorp.Cdktf (<= 0.999.0) does not contain an inclusive lower …
```
> Use explicit version range

- src/index.ts
replace it with an underscore, as we do when running cdktf get:
https://github.com/hashicorp/terraform-cdk/blob/4645749421c05515012c4891ba985285facc5603/packages/@cdktf/provider-generator/lib/get/constructs-maker.ts#L150
Resolves build failing in https://github.com/hashicorp/cdktf-provider-googlebeta/pull/2
> fix: fix package names for Java containing a hyphen

- src/index.ts
Fixes https://github.com/hashicorp/cdktf-provider-googlebeta/issues/30
> fix: remove dash from python dist and module name

- src/index.ts
- test/__snapshots__/index.test.ts.snap
- test/index.test.ts
This leads to breaking changes creating a major version bump, making
it clearer to users that the upgrade might include a breaking change
> feat: ensure we have a 1.x version in every provider

- src/index.ts
> fix: remove all dashes from go module name

- API.md
- src/index.ts
It will allow to switch memory heavy providers to custom Github Action runners with more memory
> feat: introduce useCustomGithubRunner option

- API.md
- src/index.ts
This will enable us to quickly spin up our own pre-built providers for testing purposes
> chore: make release targets more configurable

- src/provider-upgrade.ts
- test/__snapshots__/index.test.ts.snap
Fixes #268 
Per the [documentation](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions), the `.outputs` property was missing from these lines. I manually override projen to [test this on an active repository](https://github.com/skeptools/cdktf-provider-slack/actions/runs/3298230485/jobs/5440066397), and it _does_ resolve the issue.
> fix: proper reference to workflow step outputs

- src/cdktf-config.ts
- src/provider-upgrade.ts
- test/__snapshots__/index.test.ts.snap
Related to: https://github.com/hashicorp/terraform-cdk/issues/1976
This PR does the following:
- When a provider version changes, it mentions both the old and new version in the commit
- Enable `standard-version` to include `chore` commits in the change log published with each release.
This fixes part of the issue above, and another PR will be created on https://github.com/cdktf/cdktf-repository-manager which is also responsible for some Pull Requests made on the pre-built provider repositories.
> feat: Better release commits

- src/provider-upgrade.ts
- test/__snapshots__/index.test.ts.snap
The previous change changes the commit message which contains the provider versions, but didn't update the PR title. Unfortunately, I didn't realize that the updates will have the PR titles and not commit messages. This PR fixes that.
> fix: update pr title for prebuilt provider upgrade

- src/scripts/check-for-upgrades.ts
- test/__snapshots__/index.test.ts.snap
fix: fix current version lookup for providers with uppercase letters
We currently have 'Snowflake-Labs/snowflake' defined in a config. But the generated versions.json file is all lower-case.
This failed the upgrade script for this (and possibly other providers). Closes https://github.com/hashicorp/terraform-cdk/issues/2267
> fix: fix current version lookup for providers with uppercase letters

- API.md
- src/index.ts
- src/readme.ts
Fixes #270 
The first commit is all that is needed to resolve the issue.
The second commit is a bit of cleanup based on my interpretation of the difference between `namespace` (which I was taking to mean "cdktf" or something else) and `githubNamespace` (which I was seeing used as the GitHub org for both the origin repo and the destination packages). This commit is where there may be side effects - but _only if downstream repos are using non-defaults for `namespace`_. If all downstream repos are using the defaults, this change should result in zero changes in those repos. If you are uncomfortable with the change management around this, I will simply revert the second commit and leave the first one - which is all I really need. But I do think this cleanup will prevent some bugs down the …
> fix: namespace / npm scope

- src/alert-open-prs.ts
- src/index.ts
- test/__snapshots__/index.test.ts.snap
Also, move the cadence of PRs checking to twice a day
The reason for reducing the check is that it pollutes our github actions and thus makes the [dashboard](https://mutahhir.github.io/check-prebuilt-provider-status/) less useful. I think it's possible to improve that logic, but we also don't need hourly cadence for this IMO.
> chore: Add repo name to make CLI work without checking out the repo

- src/index.ts
- test/__snapshots__/index.test.ts.snap
Otherwise our documentation is incorrect as the major version goes into the import path in golang.
Also this leads to changes in a release scenario, causing an unclear build state after the bump and build during the release action
> fix: ensure golang documentation has correct package.json version on generation

- src/index.ts
- test/__snapshots__/index.test.ts.snap
https://github.com/projen/projen/pull/2472 should allow us to fix the issue of changing documentation during release permanently, this is a temporary fix until the projen PR is merged and released
Fixes #
> fix: temporarily disable golang documentation generation

- src/index.ts
- test/__snapshots__/index.test.ts.snap
we shadow projens built-in bump with our unconditional one, so we need to apply the min major version there
> fix: set min major version for unconditional bump

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/upgrade-main.yml
- .projenrc.ts
- package.json
This workflow hasn't been running for a couple of months now:   https://github.com/cdktf/cdktf-provider-project/actions/runs/5663099812/job/15344250645
I figure we can also change the upgrade schedule to weekly because we really don't need nightly Projen upgrades.
> chore: fix upgrade-main workflow

- src/index.ts
- test/__snapshots__/index.test.ts.snap
Fixes issues with go releases being blocked on prebuilt providers
> fix: Everything resides in .repo, fix source path

- src/copyright-headers.ts
- src/index.ts
- test/__snapshots__/index.test.ts.snap
All used github actions should have a pinned version at the top of index.ts. `hashicorp/setup-copywrite` was missing one, so that's fixed now.
> chore: pin hashicorp/setup-copywrite version

- src/force-release.ts
- src/index.ts
- test/__snapshots__/index.test.ts.snap
We've customized the release flow to not trigger a release unnecessarily. However, the `force-release` workflow needs to ignore that.
> chore: Create a force-release task

- src/index.ts
- test/__snapshots__/index.test.ts.snap
This can help cut down on the GitHub notification spam as well as the excessive Mergify usage. Most of the time, Projen is the only thing that gets updated anyway, and we really don't need those updates nightly.
The downside is that this also updates CDKTF patch versions, but if we ever critically need to update all providers with a patch, I suppose we could just trigger it manually from cdktf-repository-manager.
> chore: upgrade dependencies for providers weekly instead of nightly

- .projen/deps.json
- .projen/tasks.json
- .projenrc.ts
- package.json
- yarn.lock
node-fetch needs to be pinned to v2 if we don't want to use ES modules.
> chore: fix broken upgrade-node workflow

- src/provider-upgrade.ts
- test/__snapshots__/index.test.ts.snap
Use 'fix' for patch version provider upgrades, for proper semantic versioning and consistency.
> chore: use 'feat' for minor version provider upgrades

- src/readme.ts
- test/__snapshots__/index.test.ts.snap
- test/index.test.ts
Couple of minor but IMO powerful improvements to the provider READMEs:
- Puts the true underlying version number in the title instead of the tracked version (I have never ever found the tracked version to be helpful in practice)
- Includes a link to the Registry page earlier on in the document (I look for this often and hate having to scroll so far down to find it)
- Removes text about "This links to the minimum version being tracked" which is no longer relevant as a result of Mark's changes merged in #342
It's worth noting that in the snapshot tests, `underlyingTerraformVersion` is always unset, but in the actual provider repos in practice, it is always set. See here for an example: https://github.com/cdktf/cdktf-provider-aws/blob/main/README.md
> chore(docs): improve READMEs for individual providers

- src/index.ts
- test/__snapshots__/index.test.ts.snap
While working on #370, I realized that it'd be nice if the Go repos also have the same deprecation message. That got me thinking that the Go repos could use a better README in general. After doing some digging, I discovered that the full README [actually gets copied](https://github.com/cdktf/cdktf-provider-random-go/blob/main/random/README.md) into the Go repo, but it's buried a level lower so it's not visible if you're viewing [the main repo](https://github.com/cdktf/cdktf-provider-random-go/) which just has a barebones README that basically tells you nothing.
This moves the README up a level in the Go repo and then uses some `sed` black magic to remove/replace parts of the text that aren't relevant to the Go package. It isn't the prettiest code to write, but it was a fun challenge to …
> feat: publish a top-level README in Go repositories

- src/deprecate-packages.ts
- src/index.ts
- test/__snapshots__/index.test.ts.snap
Reverts #376 because I deduced the problem was introduced in a different place.
Also attempts to address problems with the Go and NPM deprecation steps that I couldn't test until after releasing Hashicups.
> fix: address problems uncovered when testing deprecating Hashicups

- src/index.ts
- test/__snapshots__/index.test.ts.snap
- test/index.test.ts
Fixes #382
The author's address was hard-coded. I made it settable from the config.
> feat: Make author address overridable

- src/deprecate-packages.ts
- test/__snapshots__/index.test.ts.snap
The release workflow allowed `is_deprecated = false` packages to still get deprecated because of some weirdness within the github actions. This should make the filter a bit more secure.
> fix: Prevent accidental package deprecations

- src/scripts/check-for-upgrades.ts
- test/__snapshots__/index.test.ts.snap
based on https://github.com/hashicorp/terraform-cdk/pull/3403
> fix(cli): Fix version range matching for 0.x version ranges with the ~> operator

- src/readme.ts
- test/__snapshots__/index.test.ts.snap
Our readme shows an incorrect command to execute for Golang in order to use the prebuilt providers within CDKTF projects.
This PR updates that language to be clearer to the users.
> chore: Fix `go get` usage for Golang within readme

- API.md
- src/index.ts
- test/index.test.ts
Fixes #385
The maven group ID starts with `com.` by default. I added an option to override the whole group ID.
> feat: Make maven group ID overridable

- .github/workflows/lock.yml
- src/lock-issues.ts
- test/__snapshots__/index.test.ts.snap
As seen in the following images, we seem to be running into a secondary rate limit when we try to lock issues within our provider repositories. 
This PR tries to use a hash of the project name to generate a somewhat unique cron schedule across all our repositories. I have to say that I haven't really thought too hard about this, so if you feel there are problems in my approach, please let me know.
> fix: Randomize locking job schedule to prevent running into github rate limits

- .github/workflows/lock.yml
- src/alert-open-prs.ts
- src/index.ts
- src/lock-issues.ts
- src/util/random-cron.ts
- test/__snapshots__/index.test.ts.snap
I noticed the lock workflow was still failing sometimes, and from what I could tell the runs that failed were most likely to be during business hours (US time). I'm hoping we can address the issue by running during the night (early morning hours UTC).
While I was at it, I refactored Mutahhir's great work into a separate script so that it could be reused across workflows; another one that makes a fair number of API calls that could benefit from this approach is the stale workflow.
> chore: improve random cron generation

- src/index.ts
- test/__snapshots__/index.test.ts.snap
Specifying multiple labels is being deprecated: https://github.blog/changelog/2024-05-16-new-dates-for-actions-larger-runner-multi-label-deprecation/
> fix: use single label for large Github runners

- src/index.ts
- test/__snapshots__/index.test.ts.snap
This used to be the default behavior but was changed in Projen in projen/projen#3526. This overrides the new behavior and reverts it to how it used to work originally.
I don't really know what problem that Projen PR was solving since you can retry individual failed steps in the release workflow; you don't have to retry the entire workflow.
On the other hand, I noticed a couple of months ago when we were having Maven publishing issues that this "fix" was actually _causing_ problems for us. Consider the following scenario:
1. Let's say we have _terraform-provider-example_ which is currently on v4.0.1, and _cdktf-provider-example_ which is currently on v12.0.1.
2. _terraform-provider-example_ publishes a new version, going from v4.0.1 -> v4.0.2
3. The nightly provider upgrade job for …
> fix(release): publish a GitHub release even if a particular package manager fails

- src/force-release.ts
- src/index.ts
- test/__snapshots__/index.test.ts.snap
For future reference, what ended up being helpful in finding the issue was comparing the publishing steps in this repo with [the ones for cdktf-tf-module-stack](https://github.com/cdktf/cdktf-tf-module-stack/blob/309f6826e9835b68dd2925d62cd33cd58e2145a1/.github/workflows/release.yml#L256-L297), which is the one other project that we have that uses Projen to publish Go modules.
> fix(release): use correct steps when publishing Go modules

- .projen/deps.json
- .projenrc.ts
- package.json
- yarn.lock
This upgrade does not apply to the prebuilt providers themselves, which were already on v5.4 anyway.
> chore(deps): upgrade JSII & TypeScript for this package only

- src/deprecate-packages.ts
- src/provider-upgrade.ts
- test/__snapshots__/index.test.ts.snap
This is probably important because of the changes in https://github.com/projen/projen/releases/tag/v0.88.0 -- let's make sure we're consistent about the version of Node.js being used in all our workflows.
> chore(ci): set Node.js version in all workflows

- src/index.ts
- src/provider-upgrade.ts
- test/__snapshots__/index.test.ts.snap
Addresses the `terraform` CLI being removed from new GitHub Actions runner images, which is preventing automated provider upgrades to happen for all of our providers that don't use custom runners.
> fix(ci): setup Terraform on ubuntu-latest

- .github/workflows/auto-approve.yml
- .github/workflows/automerge.yml
- .github/workflows/upgrade-jsii-typescript.yml
- projenrc/upgrade-jsii-typescript.ts
- projenrc/upgrade-node.ts
- src/alert-open-prs.ts
- src/auto-approve.ts
- src/auto-close-community-issues.ts
- src/automerge.ts
- src/deprecate-packages.ts
- src/lock-issues.ts
- src/provider-upgrade.ts
- test/__snapshots__/index.test.ts.snap
Found a few more instances of workflow drift between our Projen projects, addressing them in bulk here.
> chore(ci): address workflow consistency issues

- .github/workflows/auto-approve.yml
- .github/workflows/automerge.yml
- src/auto-approve.ts
- src/automerge.ts
- test/__snapshots__/index.test.ts.snap
This did not turn out to be helpful, as it's just leading to more stale PRs because sometimes the workflow fails to trigger at all.
> chore(ci): don't cancel-in-progress auto-approve and automerge workflows

- src/provider-upgrade.ts
- test/__snapshots__/index.test.ts.snap
We upgraded our custom runners to Ubuntu 24.04 yesterday, but it seems like these images no longer have Terraform installed on the command line anymore, so we now need to use the `setup-terraform` step for both custom runners and the default ones.
Without this fix, the nightly provider-upgrade jobs for big providers like Google and AWS will fail.
> chore(ci): add missing setup-terraform step to workflow

- src/force-release.ts
- test/__snapshots__/index.test.ts.snap
Turns out hard-coding array indices is a bad idea because they may not always be the same across all projects! Who woulda thunk it...
> refactor: make force-release workflow more resilient
