cdktf/cdktf-provider-project

src/index.ts

See this [comment](https://github.com/terraform-cdk-providers/cdktf-provider-null/pull/186#pullrequestreview-584349137)

Adjust naming schema for nuget

---

src/index.ts

See https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation

Nuget has reserved prefixes

---

src/provider-upgrade.ts
src/readme.ts

This adds auto generated docs generated by https://github.com/aws/jsii-docgen

Add auto generated docs

---

src/provider-upgrade.ts

Follow up to https://github.com/terraform-cdk-providers/cdktf-provider-project/pull/103

Explicitly generate docs

---

.github/workflows/build.yml
.github/workflows/release.yml
.projen/deps.json
.projen/tasks.json
package.json
src/cdktf-config.ts
src/index.ts
yarn.lock

Otherwise `cdktf@0.0.0` would be tried to be installed.
Also see https://github.com/projen/projen/issues/670

Don't Automatically Pin Peer Dependencies

---

src/cdktf-config.ts

https://github.com/hashicorp/terraform-cdk/pull/743

Bump cdktf dependency

---

src/index.ts

Upgrade minimum node version

---

src/index.ts

Provide full version

---

src/index.ts

Use most recent version of node 12 for builds in dependent packages

---

src/index.ts
yarn.lock

Use node version where types are available

---

src/auto-merge.ts
src/index.ts
src/provider-upgrade.ts

Automerge workflow

---

src/index.ts

Switch release branch to main

---

src/index.ts

Add author address

---

src/index.ts

No sample code

---

src/cdktf-config.ts

Build provider

---

src/provider-upgrade.ts

Enable creating PRs for GH Token

---

API.md
src/cdktf-config.ts
src/index.ts

Make it easier to configure these values from the outside

---

src/auto-merge.ts

Wait for 20 minutes for automerges

---

.github/workflows/build.yml
.projen/deps.json
.projen/tasks.json
.projenrc.js
package.json
src/cdktf-config.ts
test/__snapshots__/index.test.ts.snap
yarn.lock

Fixes this type of downstream problem: https://github.com/hashicorp/cdktf-provider-docker/pull/943

fix: provider build needs to have CHECKPOINT_DISABLE env var set

---

src/readme.ts
test/__snapshots__/index.test.ts.snap

chore: document go install instructions

---

src/index.ts
test/index.test.ts

fix: use gh cli to detect release status

---

src/index.ts

fix: default value messed with detection

---

src/index.ts

chore: use a null check since 0 is falsy in JS

---

src/index.ts

chore: add a few logs to check throughout the prebuilt providers

---

API.md
src/index.ts
test/__snapshots__/index.test.ts.snap
test/index.test.ts

chore: add github token to build job environment

---

src/provider-upgrade.ts
test/__snapshots__/index.test.ts.snap

chore: add gh token to fetch workflow as fetch runs projen

---

src/index.ts

This should fix the release problem temporarily

fix: never set the major version for now

---

src/index.ts

fix: go package name may not include hyphens

---

API.md
src/index.ts
test/__snapshots__/index.test.ts.snap

Prepared to be merged after repositories have been moved. Part of https://github.com/hashicorp/terraform-cdk/issues/2135

feat: switch githubNamespace to cdktf

---

src/provider-upgrade.ts
test/__snapshots__/index.test.ts.snap

See https://github.com/actions/runner/issues/866
Fixes #258

fix: Cannot use double-quotes in GitHub Actions ifs

---

src/scripts/should-release.ts
test/__snapshots__/index.test.ts.snap

fix: properly detect first release

---

src/index.ts
test/__snapshots__/index.test.ts.snap

chore: fix mergify config

---

src/index.ts
test/__snapshots__/index.test.ts.snap

chore: add auto-close for automatic prs after a day

---

src/index.ts
test/__snapshots__/index.test.ts.snap

fix: set safe.directory git option before running git

---

src/index.ts

And we know it is there already, so no harm
Fixes #

fix: use ! instead of ? to have JS compliant compiled code

---

src/index.ts
test/__snapshots__/index.test.ts.snap
test/index.test.ts

fix!: don't force a version of @cdktf/provider-project

---

src/index.ts
test/__snapshots__/index.test.ts.snap
test/index.test.ts

fix: truncate docs of >10MB length by removing following lines

---

src/index.ts
test/__snapshots__/index.test.ts.snap

This fix is instead of our upstream projen fix.

fix: fully clone the repository on build so that the bump step gets the correct version

---

src/index.ts
test/__snapshots__/index.test.ts.snap

fix: Revert package json version bump after build is complete

---

.github/workflows/build.yml
.github/workflows/upgrade-main.yml
.projenrc.ts
src/copyright-headers.ts
src/index.ts
test/__snapshots__/index.test.ts.snap

Came across a few of these while auditing for TSCCR purposes.

chore: update pinned GitHub Actions versions

---

src/index.ts
test/__snapshots__/index.test.ts.snap
test/index.test.ts

Fixes https://github.com/orgs/hashicorp/projects/168/views/14?pane=issue&itemId=34265579

feat: Add copyright headers to golang publishing

---

.github/workflows/auto-approve.yml
.github/workflows/automerge.yml
.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-main.yml
.github/workflows/upgrade-node.yml
.projenrc.ts
projenrc/auto-approve.ts
projenrc/automerge.ts
projenrc/upgrade-node.ts
src/index.ts
test/__snapshots__/index.test.ts.snap

Updates pinned GitHub Actions versions and applies a few learnings from elsewhere to improve workflows.

chore: workflow housekeeping

---

src/index.ts
test/__snapshots__/index.test.ts.snap

in past projen version it was always there

fix: check if file exists before trying to read

---

.github/workflows/auto-approve.yml
.github/workflows/automerge.yml
.github/workflows/build.yml
.github/workflows/release.yml
.github/workflows/upgrade-main.yml
.github/workflows/upgrade-node.yml
.projenrc.ts
src/index.ts
test/__snapshots__/index.test.ts.snap

This intentionally does not include the breaking change to the Slack API action.

chore(deps): update pinned versions of GitHub Actions
